apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1
    spec:
      containers:
        - name: mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: pod1-service
spec:
  selector:
    app: pod1
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-service-deployment
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-flask-service
  template:
    metadata:
      labels:
        app: my-flask-service
    spec:
      containers:
        - name: todo
          image: 475338120318.dkr.ecr.us-west-2.amazonaws.com/todo-flask-app:latest
          env:
            - name: MONGO_HOST
              value: "pod1-service"  
            - name: MONGO_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-service
spec:
  selector:
    app: my-flask-service
  ports:
    - protocol: TCP
      port: 56068
      targetPort: 5000
  type: LoadBalancer