apiVersion: v1
kind: ReplicationController
metadata:
  name: my-flask-app-rc
spec:
  replicas: 6
  selector:
    app: my-flask-rc-app
  template:
    metadata:
      labels:
        app: my-flask-rc-app
    spec:
      containers:
      - name: flask-app
        image: 475338120318.dkr.ecr.us-west-2.amazonaws.com/todo-flask-app:v3
        env:
          - name: MONGO_HOST
            value: "pod1-service"
          - name: MONGO_PORT
            value: "27017"
