apiVersion: v1
kind: Service
metadata:
  name: my-flask-service
spec:
  selector:
    app: my-flask-service
  ports:
    - protocol: TCP
      port: 56011
      targetPort: 5000
  type: LoadBalancer
