apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-service-deployment
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: my-flask-service
  template:
    metadata:
      labels:
        app: my-flask-service
    spec:
      containers:
      - name: todo
        image: 475338120318.dkr.ecr.us-west-2.amazonaws.com/todo-flask-app:v4
        env:
          - name: MONGO_HOST
            value: "pod1-service"  
          - name: MONGO_PORT
            value: "27017"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 20
          
