---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    name: pod1
spec:
  containers:
    - name: mongo
      image: mongo
      volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
  volumes:
    - name: mongo-storage
      persistentVolumeClaim:
        claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: pod1-service
spec:
  selector:
    name: pod1
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Pod
metadata:
  name: my-flask-service
  labels:
    app: my-flask-service
spec:
  containers:
    - name: todo
      image: sashankrm11/todo_app:latest
      env:
        - name: MONGO_HOST
          value: "pod1-service"
        - name: MONGO_PORT
          value: "27017"

---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-service
spec:
  selector:
    app: my-flask-service
  ports:
    - protocol: TCP
      port: 56012
      targetPort: 5000
  type: LoadBalancer
