apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: todo-mongodb
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-mongodb
  template:
    metadata:
      labels:
        app: todo-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    app: todo-app
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 2 # example of two replicas for the application
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: sashankrm11/todo_app:latest # replace with your actual image name
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_URL
            value: "mongodb://mongodb-service:27017" # This will use the service name of MongoDB to connect from the Flask app
