apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod1
  template:
    metadata:
      labels:
        app: pod1
    spec:
      containers:
        - name: mongo
          image: mongo
